MOB-289: Liveness changes
iProov/android-api-client pull request #16
Opened 2020-08-19 08:59 UTC by IgorKichenko

[JIRA Ticket](https://iproov.atlassian.net/browse/MOB-289?atlOrigin=eyJpIjoiODhkNWZkNjY4YjI4NDkyMWI3YjVkNjk4NDFkYzE3YzMiLCJwIjoiaiJ9url)

2020-08-20 08:34 UTC, richardsimongreen approved these changes

2020-08-20 08:35 UTC, richardsimongreen commented
Please update README.md

2020-08-20 08:36 UTC, richardsimongreen commented
Note to self, release as 1.1.0 after this is merged

2020-09-11 10:12 UTC, dxpelou commented on java-retrofit/src/main/java/com/iproov/androidapiclient/javaretrofit/ApiClientJavaRetrofit.java
> +                    "android",
Code style, should be inline with other parameters.

2020-09-11 10:15 UTC, dxpelou commented on kotlin-retrofit/src/main/java/com/iproov/androidapiclient/kotlinretrofit/ApiClientRetrofit.kt
> +            TokenRequest(apiKey, secret, appID, userID, assuranceType = assuranceType)
Can't this just be `assuranceType ` rather than `assuranceType = assuranceType`.

2020-09-11 10:15 UTC, dxpelou approved these changes

2020-09-11 10:24 UTC, IgorKichenko commented on kotlin-retrofit/src/main/java/com/iproov/androidapiclient/kotlinretrofit/ApiClientRetrofit.kt
> +            TokenRequest(apiKey, secret, appID, userID, assuranceType = assuranceType)
No, we are using the default value for one of the parameters(client)

2020-09-23 12:02 UTC, jonathanellis commented on README.md
> +            apiClient.getToken(ClaimType.VERIFY, userId, assuranceType).token
to align with iOS, we should make assuranceType the first parameter rather than the last (and also add an override so that it defaults to GPA)

2020-09-23 12:02 UTC, jonathanellis commented on example/src/main/java/com/iproov/androidapiclient/harness/DemoActivity.kt
> +        val assuranceType = "gpa"
should be `genuine_presence`

2020-09-23 12:02 UTC, jonathanellis commented on example/src/main/java/com/iproov/androidapiclient/harness/DemoActivity.kt
> +                    apiClient.enrolPhotoAndGetVerifyToken(userID, assuranceType, bitmap, PhotoSource.OPTICAL_ID)
we should avoid allowing setting the assurance type for `enrolPhotoAndGetVerifyToken` -- the idea is that enrolment should only be done with GPA

2020-09-23 12:02 UTC, jonathanellis commented on example/src/main/java/com/iproov/androidapiclient/harness/DemoActivity.kt
> +        val assuranceType = "gpa"
also, should we not use an enum for this?

2020-09-23 12:02 UTC, jonathanellis commented on example/src/main/java/com/iproov/androidapiclient/harness/DemoActivity.kt
> +        val assuranceType = "gpa"
same here

2020-09-23 17:22 UTC, richardsimongreen approved these changes

2020-09-23 18:14 UTC, jonathanellis requested changes

2020-09-23 18:14 UTC, jonathanellis commented on java-retrofit/src/main/java/com/iproov/androidapiclient/javaretrofit/TokenRequest.java
> +    public TokenRequest(String apiKey, String secret, String resource, String userId, String client, String assuranceType) {
we should use `AssuranceType` enum here as well

2020-09-23 18:29 UTC, jonathanellis commented on kotlin-fuel/src/main/java/com/iproov/androidapiclient/kotlinfuel/ApiClientFuel.kt
> +    getToken( AssuranceType.GENUINE_PRESENCE, ClaimType.ENROL, userID).let { token1 ->
```suggestion
    getToken(AssuranceType.GENUINE_PRESENCE, ClaimType.ENROL, userID).let { token1 ->
```

2020-09-23 18:29 UTC, jonathanellis commented on kotlin-fuel/src/main/java/com/iproov/androidapiclient/kotlinfuel/ApiClientFuel.kt
> +            getToken( AssuranceType.GENUINE_PRESENCE, ClaimType.VERIFY, userID)
```suggestion
            getToken(AssuranceType.GENUINE_PRESENCE, ClaimType.VERIFY, userID)
```

2020-09-23 18:29 UTC, jonathanellis commented on java-retrofit/src/main/java/com/iproov/androidapiclient/javaretrofit/TokenRequest.java
> +    public TokenRequest(String apiKey, String secret, String resource, String userId, String client, ApiClientJavaRetrofit.AssuranceType assuranceType) {
do we actually need the full name?

2020-09-23 18:29 UTC, jonathanellis commented on kotlin-retrofit/src/main/java/com/iproov/androidapiclient/kotlinretrofit/ApiClientRetrofit.kt
> +            TokenRequest(apiKey, secret, appID, userID, assuranceType = assuranceType.backendName)
```suggestion
            TokenRequest(apiKey, secret, appID, userID, assuranceType.backendName)
```

2020-09-23 18:33 UTC, IgorKichenko commented on java-retrofit/src/main/java/com/iproov/androidapiclient/javaretrofit/TokenRequest.java
> +    public TokenRequest(String apiKey, String secret, String resource, String userId, String client, ApiClientJavaRetrofit.AssuranceType assuranceType) {
Yes

2020-09-23 18:34 UTC, IgorKichenko commented on kotlin-retrofit/src/main/java/com/iproov/androidapiclient/kotlinretrofit/ApiClientRetrofit.kt
> +            TokenRequest(apiKey, secret, appID, userID, assuranceType = assuranceType.backendName)
We can't, we are using default value for client parameter

2020-09-23 18:39 UTC, IgorKichenko commented on java-retrofit/src/main/java/com/iproov/androidapiclient/javaretrofit/TokenRequest.java
> +    public TokenRequest(String apiKey, String secret, String resource, String userId, String client, ApiClientJavaRetrofit.AssuranceType assuranceType) {
But I changed it anyway 😂

2020-09-23 18:41 UTC, jonathanellis commented on kotlin-retrofit/src/main/java/com/iproov/androidapiclient/kotlinretrofit/ApiClientRetrofit.kt
> +            TokenRequest(apiKey, secret, appID, userID, assuranceType = assuranceType.backendName)
ah ok

2020-09-23 18:41 UTC, jonathanellis approved these changes

2020-09-23 18:43 UTC, merged